CREATE TABLE Person (
                        person_id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL
);

create table Book (
                      book_id int generated by default as identity primary key,
                      person_id int references Person (person_id) on delete set null,
                      name varchar(200) not null,
                      author varchar(200) not null,
                      year_of_production int check (year_of_production > 1000)
);


INSERT INTO book (person_id, name, author, year_of_production) VALUES
    (1, 'Война и мир', 'Лев Толстой', 1990);
INSERT INTO book (person_id, name, author, year_of_production) VALUES
    (null, 'Изучаем Java', ' Сьерра Кэти, Бэйтс Берт', 2023);


select * from person inner join book on person.person_id = book.person_id;


SELECT * FROM Person WHERE person_id = 1;


SELECT * FROM Book
