CREATE TABLE Person (
                        id int GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name varchar(100) NOT NULL UNIQUE,
                        year_of_birth int NOT NULL
);

create table Book (
                      id int generated by default as identity primary key,
                      person_id int references Person (id) on delete set null,
                      name varchar(200) not null,
                      author varchar(200) not null,
                      year_of_production int check (year_of_production > 1000)
);

INSERT INTO book (id, name, author, year_of_production) VALUES
    (1, 'Война и мир', 'Лев Толстой', 1990);
INSERT INTO book (id, name, author, year_of_production) VALUES
    (null, 'Изучаем Java', ' Сьерра Кэти, Бэйтс Берт', 2023);

INSERT INTO person (name, year_of_birth) VALUES
    ('Татаринов Антон Викторович', 1992);


INSERT INTO book (person_id, name, author, year_of_production) VALUES
    (1, 'Война и мир', 'Лев Толстой', 1990);
INSERT INTO book (person_id ,name, author, year_of_production) VALUES
    (null, 'Изучаем Java', ' Сьерра Кэти, Бэйтс Берт', 2023);



alter table Book add column taken_at TIMESTAMP

